version: '3.1'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
      - "8000:8000"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    network_mode: host
    ports:
      - "3000:3000"
    links:
      - graphite
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin